import { useNavigate } from 'react-router-dom';
import { useLive } from '../ws';
import { fmt, fmtPct, cls } from '../format';
import type { PeerInfo } from '../types';

function stanceOf(s: string): 'BUY' | 'HOLD' | 'SELL' {
  const v = s.toLowerCase();
  if (v.includes('buy')) return 'BUY';
  if (v.includes('sell')) return 'SELL';
  return 'HOLD';
}

export default function CompetitionPanel({ symbol, peers, onContext }: { symbol: string; peers: PeerInfo[]; onContext?: (q: string) => void }) {
  const navigate = useNavigate();
  const fundamentals = useLive((s) => s.fundamentals);
  const snapshots = useLive((s) => s.snapshots);

  if (!peers.length) {
    return (
      <div className="panel reveal">
        <div className="panel-title">
          <h3>Competition</h3>
          <span className="hint">peer set builds with each automation run</span>
        </div>
        <div className="empty">Competitor universe for {symbol} is pending — generated by the next automation run (Yahoo peer list + same-industry names).</div>
      </div>
    );
  }

  return (
    <div className="panel reveal">
      <div className="panel-title">
        <h3>Competition — {symbol}</h3>
        <span className="hint">{peers.length} peers · hover for our view · click to drill in</span>
      </div>
      <div className="peer-grid">
        {peers.map((p) => {
          const a = fundamentals[p.symbol];
          const s = snapshots[p.symbol];
          const stance = a ? (a.opinion?.stance ?? stanceOf(a.verdict.rating)) : 'HOLD';
          const price = s?.price ?? a?.price;
          const change = s?.changePct;
          const why = a?.opinion?.thesis ?? a?.verdict?.summary ?? 'Analysis pending — generated by the automation pipeline.';
          return (
            <div key={p.symbol} className="peer-card" onClick={() => navigate(`/stock/${p.symbol}`)}>
              <div className="peer-top">
                <span className="sym">{p.symbol}</span>
                <span className={cls('pill-bias', stance === 'BUY' ? 'bullish' : stance === 'SELL' ? 'bearish' : 'neutral')}>{stance}</span>
              </div>
              <div className="peer-name">{p.name ?? p.symbol}</div>
              <div className="peer-sec dim">
                {p.industry ?? p.sector ?? '—'}
              </div>
              <div className="peer-meta">
                <span className="px mono">{price != null ? fmt(price) : '—'}</span>
                {change != null && (
                  <span className={cls('mono', change >= 0 ? 'up' : 'down')}>{fmtPct(change)}</span>
                )}
              </div>
              <div className="peer-why">
                <span className="pw-label">Our view</span>
                <span className="pw-text">{why}</span>
                <button className="pw-open" onClick={(e) => { e.stopPropagation(); onContext?.(`compare ${symbol} vs ${p.symbol}`); }}>
                  Ask AI to compare →
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}