import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { get } from '../api';
import { useLive } from '../ws';
import { fmt, fmtPct, fmtCompact, cls } from '../format';
import type { Instrument, Snapshot, HistoryRow } from '../types';
import { Sparkline } from '../components/Sparkline';
import SignalFeed from '../components/SignalFeed';
import NewsFeed from '../components/NewsFeed';

function SparkHistory({ symbol }: { symbol: string }) {
  const stored = useLive((s) => s.sparklines)[symbol];
  const [closes, setCloses] = useState<number[]>([]);
  useEffect(() => {
    let live = true;
    // intraday 1-day closes via the serverless relay — matches today's action
    get<{ rows: HistoryRow[] }>(`/api/chart?symbol=${encodeURIComponent(symbol)}&range=1d`)
      .then((r) => {
        if (live && Array.isArray(r.rows) && r.rows.length > 1) setCloses(r.rows.map((c) => c.c));
      })
      .catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [symbol]);
  const closes2 = closes.length > 1 ? closes : stored?.length ? stored.map((p) => p[1]) : [];
  const up = closes2.length ? closes2[closes2.length - 1] >= closes2[0] : true;
  return <Sparkline points={closes2} up={up} />;
}

/** In snapshot/offline mode, surface when the data was last generated by CI. */
function SnapshotMeta() {
  const mode = useLive((s) => s.mode);
  const at = useLive((s) => s.snapshotAt);
  if (mode !== 'snapshot' || !at) return null;
  return (
    <div
      className="status-banner status-snapshot"
      style={{ marginBottom: 18, borderRadius: 8, border: '1px solid rgba(76,201,240,0.25)' }}
    >
      <span className="sb-icon">⏱</span>
      <span>
        Showing latest automation snapshot from <em style={{ color: 'var(--cyan)' }}>{new Date(at).toLocaleString()}</em>
        <em>live backend not deployed — data updates on each CI run</em>
      </span>
    </div>
  );
}

export default function Dashboard() {
  const navigate = useNavigate();
  const snapshots = useLive((s) => s.snapshots);
  const signals = useLive((s) => s.signals);
  const news = useLive((s) => s.news);
  const overview = useLive((s) => s.overview);
  const storeInstruments = useLive((s) => s.instruments);
  const fundamentals = useLive((s) => s.fundamentals);
  const [instruments, setInstruments] = useState<Instrument[]>([]);

  useEffect(() => {
    setInstruments(storeInstruments);
    get<Instrument[]>('/api/instruments')
      .then((rows) => rows.length && setInstruments(rows))
      .catch(() => {});
  }, [storeInstruments]);

  const live = useMemo(() => {
    const list = Object.values(snapshots).filter(Boolean) as Snapshot[];
    const bySym = new Map(list.map((s) => [s.symbol, s]));
    const gainers = [...list].sort((a, b) => b.changePct - a.changePct).slice(0, 8);
    const losers = [...list].sort((a, b) => a.changePct - b.changePct).slice(0, 8);
    return { list, bySym, gainers, losers };
  }, [snapshots]);

  // Analyst picks: best overall verdict score with positive margin of safety.
  const picks = useMemo(() => {
    const arr = Object.values(fundamentals).filter((f) => f.verdict?.score).map((f) => f);
    return arr
      .sort((a, b) => b.verdict.score - a.verdict.score || b.verdict.marginOfSafety - a.verdict.marginOfSafety)
      .slice(0, 6);
  }, [fundamentals]);

  const total = live.list.length || overview?.market.total || 0;
  const adv = overview?.market.advancers ?? live.list.filter((s) => s.changePct > 0).length;
  const dec = overview?.market.decliners ?? live.list.filter((s) => s.changePct < 0).length;
  const breadth = total ? (adv / total) * 100 : 0;

  const index = overview?.index;

  const sectors = (overview?.sectorPerformance ?? []).map((s) => {
    const pct = s.changePct;
    return { ...s, pct };
  });

  const sectorMin = sectors.length ? Math.min(...sectors.map((s) => s.pct)) : 0;
  const sectorMax = sectors.length ? Math.max(...sectors.map((s) => s.pct)) : 0;

  return (
    <div>
      <h1 style={{ marginBottom: 4 }}>Market Dashboard</h1>
      <p className="muted" style={{ marginBottom: 20, fontSize: 13 }}>
        Real NSE (National Stock Exchange) data — quotes, signals and fills across all strategies.
      </p>
      <SnapshotMeta />

      <div className="stat-grid">
        <div className="stat-card reveal">
          <div className="stat-label">NIFTY 50 Index</div>
          <div className="stat-value mono">{index ? fmt(index.price) : <span className="skeleton">00000</span>}</div>
          <div className="stat-sub">
            {index ? (
              <span className={index.changePct >= 0 ? 'up' : 'down'}>{fmtPct(index.changePct)}</span>
            ) : null}
            <span className="dim">today</span>
          </div>
        </div>
        <div className="stat-card reveal reveal-1">
          <div className="stat-label">Advancers / Decliners</div>
          <div className="stat-value mono">
            <span className="up">{adv}</span>
            <span className="dim"> / </span>
            <span className="down">{dec}</span>
          </div>
          <div className="stat-sub">
            <span style={{ display: 'inline-block', width: 130, height: 5, background: 'rgba(255,255,255,0.06)', borderRadius: 3, overflow: 'hidden' }}>
              <span style={{ display: 'block', width: `${breadth}%`, height: '100%', background: 'linear-gradient(90deg,var(--down),var(--amber),var(--up))' }} />
            </span>
            <span className="dim">{total} stocks</span>
          </div>
        </div>
        <div className="stat-card reveal reveal-2">
          <div className="stat-label">Live Signals</div>
          <div className="stat-value mono">{signals.length}</div>
          <div className="stat-sub">
            <span className="cyan">across</span>
            <span className="dim">strategies</span>
          </div>
        </div>
        <div className="stat-card reveal reveal-3">
          <div className="stat-label">News Sentiment</div>
          <div className="stat-value mono">{news.length ? `${Math.round((news.filter((n) => n.sentiment === 'BULLISH').length / news.length) * 100)}%` : '—'}</div>
          <div className="stat-sub">
            <span className="up">positive</span>
            <span className="dim">in feed</span>
          </div>
        </div>
      </div>

      <div className="grid-2-1" style={{ marginBottom: 16 }}>
        <div className="panel reveal reveal-1" style={{ minHeight: 380 }}>
          <div className="panel-title">
            <h3>Market Movers</h3>
            <span className="hint">click to drill in</span>
          </div>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Symbol</th>
                  <th>Last</th>
                  <th>Day Trend</th>
                  <th>Chg %</th>
                  <th>Volume</th>
                </tr>
              </thead>
              <tbody>
                {live.gainers.map((s) => {
                  const inst = instruments.find((i) => i.symbol === s.symbol);
                  return (
                    <tr key={s.symbol} onClick={() => navigate(`/stock/${s.symbol}`)}>
                      <td>
                        <div className="sym-cell">{s.symbol}</div>
                        <div className="name-cell">{inst?.name ?? ''}</div>
                      </td>
                      <td className="mono">{fmt(s.price)}</td>
                      <td><SparkHistory symbol={s.symbol} /></td>
                      <td className="mono"><span className={s.changePct >= 0 ? 'up' : 'down'}>{fmtPct(s.changePct)}</span></td>
                      <td className="mono muted">{fmtCompact(s.dayVolume)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        <div className="panel reveal reveal-2" style={{ minHeight: 380 }}>
          <div className="panel-title">
            <h3>Sector Performance</h3>
            <span className="hint">by avg change</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
            {sectors.map((s) => (
              <div key={s.sector}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
                  <span className="muted" style={{ fontSize: 12 }}>{s.sector}</span>
                  <span className={cls('mono', s.pct >= 0 ? 'up' : 'down')} style={{ fontSize: 12, fontWeight: 600 }}>{fmtPct(s.pct)}</span>
                </div>
                <div style={{ height: 5, background: 'rgba(255,255,255,0.05)', borderRadius: 3, overflow: 'hidden' }}>
                  <span
                    style={{
                      display: 'block',
                      height: '100%',
                      width: `${sectorMax !== sectorMin ? ((s.pct - sectorMin) / (sectorMax - sectorMin)) * 100 : 50}%`,
                      background: s.pct >= 0 ? 'linear-gradient(90deg,#00b877,var(--up))' : 'linear-gradient(90deg,#e04343,var(--down))',
                    }}
                  />
                </div>
              </div>
            ))}
            {sectors.length === 0 && <div className="empty">No sector data.</div>}
          </div>
        </div>
      </div>

      <div className="grid-2" style={{ marginBottom: 16 }}>
        <div className="panel reveal reveal-1">
          <div className="panel-title">
            <h3>Top Losers</h3>
            <span className="hint">today</span>
          </div>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Symbol</th>
                  <th>Last</th>
                  <th>Chg %</th>
                </tr>
              </thead>
              <tbody>
                {live.losers.map((s) => (
                  <tr key={s.symbol} onClick={() => navigate(`/stock/${s.symbol}`)}>
                    <td className="sym-cell">{s.symbol}</td>
                    <td className="mono">{fmt(s.price)}</td>
                    <td className="mono down">{fmtPct(s.changePct)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="panel reveal reveal-2">
          <div className="panel-title">
            <h3>Live News</h3>
            <span className="hint">streaming · market.news</span>
          </div>
          <div style={{ maxHeight: 300, overflowY: 'auto' }}>
            <NewsFeed items={news} limit={8} />
          </div>
        </div>
      </div>

      <div className="panel reveal reveal-1" style={{ marginBottom: 16 }}>
        <div className="panel-title">
          <h3>Analyst Picks</h3>
          <span className="hint">Buffett · Lynch · Graham blended score</span>
        </div>
        {picks.length ? (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Symbol</th>
                  <th>Name</th>
                  <th>Last</th>
                  <th>Fair Value</th>
                  <th>MoS</th>
                  <th>Rating</th>
                  <th>Score</th>
                </tr>
              </thead>
              <tbody>
                {picks.map((p) => (
                  <tr key={p.symbol} onClick={() => navigate(`/stock/${p.symbol}`)}>
                    <td className="sym-cell">{p.symbol}</td>
                    <td className="name-cell">{p.name ?? ''}</td>
                    <td className="mono">{fmt(p.price)}</td>
                    <td className="mono">{fmt(p.verdict.fairValueMid)}</td>
                    <td className={cls('mono', p.verdict.marginOfSafety >= 0 ? 'up' : 'down')}>
                      {p.verdict.marginOfSafety > 0 ? '+' : ''}{p.verdict.marginOfSafety}%
                    </td>
                    <td className="mono" style={{ color: p.verdict.rating === 'Strong Buy' || p.verdict.rating === 'Buy' ? 'var(--up)' : p.verdict.rating === 'Hold' ? 'var(--amber)' : 'var(--down)' }}>
                      {p.verdict.rating}
                    </td>
                    <td className="mono"><b>{p.verdict.score}</b> <span className="dim">/100</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="empty">Analyst model builds with each automation run.</div>
        )}
      </div>

      <div className="panel reveal reveal-1">
        <div className="panel-title">
          <h3>Algorithm Signals</h3>
          <span className="hint">streaming · market.signals</span>
        </div>
        <SignalFeed signals={signals} limit={25} />
      </div>
    </div>
  );
}
