import { useEffect, useState } from 'react';

interface PosRow {
  strategy: string;
  label: string;
  symbol: string;
  qty: number;
  entryPrice: number;
  lastPrice: number;
  unrealized: number;
  unrealizedPct: number;
  heldDays: number;
}

interface StrategyRow {
  id: string;
  label: string;
  allocPct: number;
  cash: number;
  positionEquity: number;
  equity: number;
  pnl: number;
  trades: number;
  wins: number;
  losses: number;
  winRate: number | null;
  open: { symbol: string; qty: number; entryPrice: number; heldDays: number } | null;
}

interface TradeRow {
  day: string;
  time?: string;
  strategy: string;
  symbol: string;
  side: 'BUY' | 'SELL';
  qty: number;
  price: number;
  pnl: number;
  reason: string;
  entryPrice?: number;
  stopLoss?: number;
  trailStop?: number;
  retPct?: number | null;
  exitClass?: string;
  story?: string;
}

interface PaperReport {
  ts: string;
  account: string;
  initialCapital: number;
  asOf: string;
  seeded: boolean;
  cash: number;
  equity: number;
  invested: number;
  realizedPnl: number;
  unrealizedPnl: number;
  dayPnl: number;
  totalReturnPct: number;
  tradingDays: number;
  slPct?: number;
  trailPct?: number;
  maxHoldDays?: number;
  strategies: StrategyRow[];
  openPositions: PosRow[];
  recentTrades: TradeRow[];
  transactions?: TradeRow[];
  history: { date: string; equity: number; cash: number; invested: number }[];
}

const DAILY_URLS = [
  'https://cdn.jsdelivr.net/gh/amant03/trading_algo@automation-data/frontend/public/paper/daily.json',
  'https://raw.githubusercontent.com/amant03/trading_algo/automation-data/frontend/public/paper/daily.json',
  '/paper/daily.json',
];

interface DailyReport {
  ts: string;
  today: {
    date: string;
    startCapital: number;
    capital: number;
    equity: number;
    realizedPnl: number;
    dayPnl: number;
    wins: number;
    losses: number;
    trades: TradeRow[];
    open: { strategy: string; symbol: string; qty: number; entryPrice: number; lastPrice: number }[];
    status: 'pre-open' | 'open' | 'closed' | 'holiday';
    bars: number;
    updatedAt: string;
  } | null;
  days: { date: string; capital: number; equity: number; realizedPnl: number; dayPnl: number; wins: number; trades: number; winPct?: number | null }[];
}

const PAPER_URLS = [
  '/paper/latest.json',
  'https://cdn.jsdelivr.net/gh/amant03/trading_algo@automation-data/frontend/public/paper/latest.json',
  'https://raw.githubusercontent.com/amant03/trading_algo/automation-data/frontend/public/paper/latest.json',
];

const STRAT_META_LABELS = new Map([
  ['ma_cross', 'MA Cross'],
  ['rsi_reversal', 'RSI Reversal'],
  ['macd_cross', 'MACD Cross'],
  ['bb_breakout', 'Bollinger'],
  ['supertrend', 'Supertrend'],
]);

const inr = (n: number | null | undefined, digits = 0): string =>
  n == null || !isFinite(n) ? '—' : `₹${n.toLocaleString('en-IN', { maximumFractionDigits: digits })}`;

const pnlCls = (n: number | null | undefined): string => (n == null ? '' : n > 0.005 ? 'up' : n < -0.005 ? 'down' : '');

function Spark({ series }: { series: { equity: number }[] }) {
  if (series.length < 2) return <div className="empty" style={{ minHeight: 120 }}>Equity curve builds after the first daily runs.</div>;
  const w = 640;
  const h = 150;
  const vals = series.map((p, i) => ({ x: i, y: p.equity }));
  const min = Math.min(...vals.map((v) => v.y));
  const max = Math.max(...vals.map((v) => v.y));
  const span = Math.max(max - min, 1);
  const pts = vals.map((v) => `${((v.x / (series.length - 1)) * w).toFixed(1)},${(h - ((v.y - min) / span) * (h - 10) - 5).toFixed(1)}`).join(' ');
  const up = vals[vals.length - 1].y >= vals[0].y;
  const color = up ? 'var(--up)' : 'var(--down)';
  const lastY = pts.split(' ').pop()!.split(',')[1];
  return (
    <svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" style={{ width: '100%', height: 150, display: 'block' }}>
      <polyline points={pts} fill="none" stroke={color} strokeWidth="2" />
      <circle cx={w - 2} cy={lastY} r="3.2" fill={color} />
    </svg>
  );
}

export default function Paper() {
  const [report, setReport] = useState<PaperReport | null>(null);
  const [daily, setDaily] = useState<DailyReport | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let live = true;
    const load = async () => {
      for (const url of PAPER_URLS) {
        try {
          const res = await fetch(url, { cache: 'no-store' });
          if (!res.ok) continue;
          const ct = res.headers.get('content-type') ?? '';
          if (ct.includes('text/html')) continue;
          const data = (await res.json()) as PaperReport;
          if (!data?.equity) continue;
          if (live) {
            setReport(data);
            setErr(null);
          }
          return;
        } catch {
          // try next mirror
        }
      }
      if (live && !report) setErr('Paper account report not published yet — it is generated by the nightly automation run.');
    };
    void load();
    const t = setInterval(load, 60_000);
    return () => {
      live = false;
      clearInterval(t);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    let live = true;
    const load = async () => {
      for (const url of DAILY_URLS) {
        try {
          const res = await fetch(url, { cache: 'no-store' });
          if (!res.ok) continue;
          const ct = res.headers.get('content-type') ?? '';
          if (ct.includes('text/html')) continue;
          const data = (await res.json()) as DailyReport;
          if (!data?.today) continue;
          if (live) setDaily(data);
          return;
        } catch { /* try next */ }
      }
    };
    void load();
    const t = setInterval(load, 30_000);
    return () => { live = false; clearInterval(t); };
  }, []);

  const r = report;

  return (
    <div>
      <div className="stock-header">
        <div className="stock-title">
          <div className="sym">PAPER</div>
          <div className="nm">
            {r?.account ?? 'Paper Lab'} · virtual ₹1,00,000 · 5 methods
          </div>
        </div>
        <div className="stock-price-block" style={{ textAlign: 'right' }}>
          <div className={clsPnL(r ? r.equity - r.initialCapital : null)}>{r ? inr(r.equity) : '…'}</div>
          <div className={clsPnL(r?.totalReturnPct ?? null)}>
            {r ? `${r.totalReturnPct >= 0 ? '+' : ''}${r.totalReturnPct}% total · ${r.asOf || '—'}` : 'loading'}
          </div>
        </div>
      </div>

      {err && <div className="empty">{err}</div>}
      {!r && !err && !daily && <div className="empty">Loading paper account…</div>}

      {/* ================= Daily Paper trade ================= */}
      {daily && daily.today && (
        <div className="panel reveal" style={{ marginBottom: 16 }}>
          <div className="panel-title">
            <h3>Daily Paper trade</h3>
            <span className="hint">
              fresh ₹1,00,000 · 5 methods · intraday 5-min bars
              {daily.today.status === 'open' && ' · market open'}
              {daily.today.status === 'closed' && ' · session closed'}
              {daily.today.status === 'holiday' && ' · no session today'}
            </span>
          </div>
          <div className="stat-grid" style={{ marginBottom: 12 }}>
            <div className="stat-card">
              <div className="stat-label">Day P&L</div>
              <div className={clsPnL(daily.today.dayPnl)}>{inr(daily.today.dayPnl)}</div>
              <div className="stat-sub">
                {daily.today.dayPnl >= 0 ? '+' : ''}{((daily.today.dayPnl / daily.today.startCapital) * 100).toFixed(2)}%
                · {daily.today.wins}W / {daily.today.losses}L
              </div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Equity</div>
              <div className="mono">{inr(daily.today.equity)}</div>
              <div className="stat-sub">{daily.today.bars} bars · status {daily.today.status}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Cash</div>
              <div className="mono">{inr(daily.today.capital)}</div>
              <div className="stat-sub">{((daily.today.capital / daily.today.startCapital) * 100).toFixed(1)}% parked</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Open positions</div>
              <div className="mono">{daily.today.open.length}</div>
              <div className="stat-sub">refreshes every 30s during market hours</div>
            </div>
          </div>

          {daily.today.open.length > 0 && (
            <div className="table" style={{ marginBottom: 12 }}>
              <div className="tr head">
                <span>Method</span><span>Symbol</span><span>Qty</span><span>Entry</span><span>Last</span><span>Unrealised</span>
              </div>
              {daily.today.open.map((o) => {
                const ret = ((o.lastPrice / o.entryPrice) - 1) * 100;
                return (
                  <div key={o.strategy} className="tr">
                    <span className="muted">{STRAT_META_LABELS.get(o.strategy) ?? o.strategy}</span>
                    <span><a className="mono" href={`#/stock/${o.symbol}`}>{o.symbol}</a></span>
                    <span className="mono">{o.qty}</span>
                    <span className="mono">{inr(o.entryPrice, 2)}</span>
                    <span className="mono">{inr(o.lastPrice, 2)}</span>
                    <span className={clsPnL((o.lastPrice - o.entryPrice) * o.qty)}>
                      {inr((o.lastPrice - o.entryPrice) * o.qty)} ({ret >= 0 ? '+' : ''}{ret.toFixed(1)}%)
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {daily.today.trades.length > 0 && (
            <div className="table paper-ledger">
              <div className="tr head">
                <span>Time</span><span>Method</span><span>Symbol</span><span>Side</span><span>Qty</span><span>Price</span><span>P&L</span><span>Why</span>
              </div>
              {daily.today.trades.map((t, i) => (
                <div key={i} className="tr">
                  <span className="mono muted">{t.time}</span>
                  <span className="muted">{STRAT_META_LABELS.get(t.strategy) ?? t.strategy}</span>
                  <span className="mono">{t.symbol}</span>
                  <span className={t.side === 'BUY' ? 'up' : 'down'}>{t.side}</span>
                  <span className="mono">{t.qty}</span>
                  <span className="mono">{inr(t.price, 2)}</span>
                  <span className={clsPnL(t.pnl)}>{t.side === 'SELL' ? `${inr(t.pnl)}${t.retPct != null ? ` (${t.retPct >= 0 ? '+' : ''}${t.retPct}%)` : ''}` : '—'}</span>
                  <span className="muted" style={{ fontSize: 12 }}>{t.reason}</span>
                </div>
              ))}
            </div>
          )}

          {daily.days.length > 0 && (
            <div style={{ marginTop: 10, padding: '8px 4px 0', borderTop: '1px solid rgba(148,163,184,0.08)' }}>
              <div className="muted" style={{ fontSize: 12, marginBottom: 6, fontWeight: 600 }}>Recent days</div>
              <div className="table">
                <div className="tr head">
                  <span>Date</span><span>P&L</span><span>Trades</span><span>Win %</span>
                </div>
                {daily.days.slice(0, 10).map((d) => (
                  <div key={d.date} className="tr">
                    <span className="mono muted">{d.date}</span>
                    <span className={clsPnL(d.dayPnl)}>{inr(d.dayPnl)} ({d.dayPnl >= 0 ? '+' : ''}{((d.dayPnl / 100000) * 100).toFixed(2)}%)</span>
                    <span className="mono">{d.trades}</span>
                    <span className="mono">{d.winPct != null ? `${d.winPct}%` : '—'}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
      {!daily && (
        <div className="panel reveal" style={{ marginBottom: 16 }}>
          <div className="panel-title">
            <h3>Daily Paper trade</h3>
            <span className="hint">fresh ₹1,00,000 every market day · intraday 5-min bars · 5 methods</span>
          </div>
          <div className="empty">Daily paper trades refresh during market hours — first session runs at 09:16 IST.</div>
        </div>
      )}
      {/* ================= End Daily Paper trade ================= */}

      {r && (
        <div>
          <div className="panel reveal" style={{ marginBottom: 12, padding: '10px 12px' }}>
            <div className="panel-title" style={{ marginBottom: 0 }}>
              <h3>Swing Lab</h3>
              <span className="hint">₹1,00,000 · 5 buckets · multi-day hold · daily close replay</span>
            </div>
          </div>
          <div className="stat-grid" style={{ marginBottom: 16 }}>
            <div className="stat-card">
              <div className="stat-label">Day P&L</div>
              <div className={clsPnL(r.dayPnl)}>{inr(r.dayPnl)}</div>
              <div className="stat-sub">change since last processed day</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Cash</div>
              <div className="mono">{inr(r.cash)}</div>
              <div className="stat-sub">{((r.cash / r.initialCapital) * 100).toFixed(1)}% parked</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Invested</div>
              <div className="mono">{inr(r.invested)}</div>
              <div className="stat-sub">{((r.invested / r.initialCapital) * 100).toFixed(0)}% of capital at work</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Realized / Unrealized</div>
              <div className={clsPnL(r.realizedPnl)}>{inr(r.realizedPnl)} / <span className={clsPnL(r.unrealizedPnl)}>{inr(r.unrealizedPnl)}</span></div>
              <div className="stat-sub">{r.tradingDays} trading days processed</div>
            </div>
          </div>

          <div className="panel reveal" style={{ marginBottom: 16 }}>
            <div className="panel-title">
              <h3>Equity curve</h3>
              <span className="hint">
                daily MTM on real NSE closes {r.seeded ? '· seeded from ~90d history, then advanced daily' : '· live daily advancement'}
              </span>
            </div>
            <Spark series={r.history} />
          </div>

          <div className="grid-2" style={{ marginBottom: 16 }}>
            <div className="panel reveal">
              <div className="panel-title">
                <h3>Method scorecards</h3>
                <span className="hint">₹20,000 allocated to each</span>
              </div>
              <div className="strat-grid">
                {r.strategies.map((s) => (
                  <div key={s.id} className="strat-card">
                    <div className="strat-head">
                      <span className="strat-name">{s.label}</span>
                      <span className={clsPnL(s.pnl)}>{inr(s.pnl)}</span>
                    </div>
                    <div className="strat-row">
                      <span>Equity</span><b>{inr(s.equity)}</b>
                    </div>
                    <div className="strat-row">
                      <span>Book ₹{Math.round(s.allocPct)}% alloc</span>
                      <b className="mono">{s.trades} trades</b>
                    </div>
                    {s.open && (
                      <div className="strat-open">
                        {s.open.symbol} · {s.open.qty} sh @ {inr(s.open.entryPrice)} · {s.open.heldDays}d
                      </div>
                    )}
                    {!s.open && <div className="strat-open muted">flat — in cash</div>}
                  </div>
                ))}
              </div>
            </div>

            <div className="panel reveal reveal-1">
              <div className="panel-title">
                <h3>Open positions</h3>
                <span className="hint">marked to the latest daily close</span>
              </div>
              {r.openPositions.length ? (
                <div className="table">
                  <div className="tr head">
                    <span>Method</span><span>Symbol</span><span>Qty</span><span>Entry</span><span>Last</span><span>P&L</span>
                  </div>
                  {r.openPositions.map((p) => (
                    <div className="tr" key={p.strategy + p.symbol}>
                      <span className="muted">{p.label}</span>
                      <span><a className="mono" href={`#/stock/${p.symbol}`}>{p.symbol}</a></span>
                      <span className="mono">{p.qty}</span>
                      <span className="mono">{inr(p.entryPrice, 2)}</span>
                      <span className="mono">{inr(p.lastPrice, 2)}</span>
                      <span className={clsPnL(p.unrealized)}>{inr(p.unrealized)} <small>({p.unrealizedPct >= 0 ? '+' : ''}{p.unrealizedPct}%)</small></span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="empty">No open positions — all buckets in cash.</div>
              )}
            </div>
          </div>

          <div className="panel reveal">
            <div className="panel-title">
              <h3>Full transaction list</h3>
              <span className="hint">
                every fill · 8% hard stop · 12% trailing stop · 20-day max hold
                {r.slPct ? ` · SL ${(r.slPct * 100).toFixed(0)}%` : ''}
              </span>
            </div>
            <div className="muted" style={{ fontSize: 12.5, lineHeight: 1.55, padding: '0 4px 10px' }}>
              Think of each method as a separate ₹20,000 envelope. A <b>BUY</b> spends the envelope on one stock when its rule fires.
              A <b>SELL</b> is either the rule reversing, the 8% safety-net (stop-loss) cutting a loser, the trailing stop locking a winner,
              or the 20-day time limit recycling the cash. The “plain English” column is the same decision, without the jargon.
            </div>
            <div className="table paper-ledger">
              <div className="tr head">
                <span>Day</span><span>Method</span><span>Symbol</span><span>Side</span><span>Qty</span><span>Price</span><span>Stop</span><span>P&amp;L</span><span>Why</span>
              </div>
              {(r.transactions ?? r.recentTrades).map((t, i) => (
                <div key={`${t.day}-${t.strategy}-${t.symbol}-${i}`}>
                  <div className="tr">
                    <span className="mono muted">{t.day}</span>
                    <span className="muted">{t.strategy}</span>
                    <span className="mono">{t.symbol}</span>
                    <span className={t.side === 'BUY' ? 'up' : 'down'}>{t.side}</span>
                    <span className="mono">{t.qty}</span>
                    <span className="mono">{inr(t.price, 2)}</span>
                    <span className="mono muted">{t.stopLoss != null ? inr(t.stopLoss, 2) : '—'}</span>
                    <span className={clsPnL(t.pnl)}>{t.side === 'SELL' ? `${inr(t.pnl)}${t.retPct != null ? ` (${t.retPct >= 0 ? '+' : ''}${t.retPct}%)` : ''}` : '—'}</span>
                    <span className="muted" style={{ fontSize: 12 }}>{t.reason}</span>
                  </div>
                  {t.story && (
                    <div className="paper-story">{t.story}</div>
                  )}
                </div>
              ))}
              {!(r.transactions ?? r.recentTrades).length && <div className="empty">No trades yet — first run opens positions from the seed window.</div>}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function clsPnL(n: number | null | undefined): string {
  return n == null ? '' : n > 0.005 ? 'up' : n < -0.005 ? 'down' : 'muted';
}