import { useEffect, useState } from 'react';

interface PosRow {
  strategy: string;
  label: string;
  symbol: string;
  qty: number;
  entryPrice: number;
  lastPrice: number;
  unrealized: number;
  unrealizedPct: number;
  heldDays: number;
}

interface StrategyRow {
  id: string;
  label: string;
  allocPct: number;
  cash: number;
  positionEquity: number;
  equity: number;
  pnl: number;
  trades: number;
  wins: number;
  losses: number;
  winRate: number | null;
  open: { symbol: string; qty: number; entryPrice: number; heldDays: number } | null;
}

interface TradeRow {
  day: string;
  strategy: string;
  symbol: string;
  side: 'BUY' | 'SELL';
  qty: number;
  price: number;
  pnl: number;
  reason: string;
}

interface PaperReport {
  ts: string;
  account: string;
  initialCapital: number;
  asOf: string;
  seeded: boolean;
  cash: number;
  equity: number;
  invested: number;
  realizedPnl: number;
  unrealizedPnl: number;
  dayPnl: number;
  totalReturnPct: number;
  tradingDays: number;
  strategies: StrategyRow[];
  openPositions: PosRow[];
  recentTrades: TradeRow[];
  history: { date: string; equity: number; cash: number; invested: number }[];
}

const PAPER_URLS = [
  '/paper/latest.json',
  'https://cdn.jsdelivr.net/gh/amant03/trading_algo@automation-data/frontend/public/paper/latest.json',
  'https://raw.githubusercontent.com/amant03/trading_algo/automation-data/frontend/public/paper/latest.json',
];

const inr = (n: number | null | undefined, digits = 0): string =>
  n == null || !isFinite(n) ? '—' : `₹${n.toLocaleString('en-IN', { maximumFractionDigits: digits })}`;

const pnlCls = (n: number | null | undefined): string => (n == null ? '' : n > 0.005 ? 'up' : n < -0.005 ? 'down' : '');

function Spark({ series }: { series: { equity: number }[] }) {
  if (series.length < 2) return <div className="empty" style={{ minHeight: 120 }}>Equity curve builds after the first daily runs.</div>;
  const w = 640;
  const h = 150;
  const vals = series.map((p, i) => ({ x: i, y: p.equity }));
  const min = Math.min(...vals.map((v) => v.y));
  const max = Math.max(...vals.map((v) => v.y));
  const span = Math.max(max - min, 1);
  const pts = vals.map((v) => `${((v.x / (series.length - 1)) * w).toFixed(1)},${(h - ((v.y - min) / span) * (h - 10) - 5).toFixed(1)}`).join(' ');
  const up = vals[vals.length - 1].y >= vals[0].y;
  const color = up ? 'var(--up)' : 'var(--down)';
  const lastY = pts.split(' ').pop()!.split(',')[1];
  return (
    <svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" style={{ width: '100%', height: 150, display: 'block' }}>
      <polyline points={pts} fill="none" stroke={color} strokeWidth="2" />
      <circle cx={w - 2} cy={lastY} r="3.2" fill={color} />
    </svg>
  );
}

export default function Paper() {
  const [report, setReport] = useState<PaperReport | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let live = true;
    const load = async () => {
      for (const url of PAPER_URLS) {
        try {
          const res = await fetch(url, { cache: 'no-store' });
          if (!res.ok) continue;
          const ct = res.headers.get('content-type') ?? '';
          if (ct.includes('text/html')) continue;
          const data = (await res.json()) as PaperReport;
          if (!data?.equity) continue;
          if (live) {
            setReport(data);
            setErr(null);
          }
          return;
        } catch {
          // try next mirror
        }
      }
      if (live && !report) setErr('Paper account report not published yet — it is generated by the nightly automation run.');
    };
    void load();
    const t = setInterval(load, 60_000);
    return () => {
      live = false;
      clearInterval(t);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const r = report;

  return (
    <div>
      <div className="stock-header">
        <div className="stock-title">
          <div className="sym">PAPER</div>
          <div className="nm">
            {r?.account ?? 'Paper Lab'} · virtual ₹1,00,000 · 5 methods
          </div>
        </div>
        <div className="stock-price-block" style={{ textAlign: 'right' }}>
          <div className={clsPnL(r ? r.equity - r.initialCapital : null)}>{r ? inr(r.equity) : '…'}</div>
          <div className={clsPnL(r?.totalReturnPct ?? null)}>
            {r ? `${r.totalReturnPct >= 0 ? '+' : ''}${r.totalReturnPct}% total · ${r.asOf || '—'}` : 'loading'}
          </div>
        </div>
      </div>

      {err && <div className="empty">{err}</div>}
      {!r && !err && <div className="empty">Loading paper account…</div>}
      {r && (
        <div>
          <div className="stat-grid" style={{ marginBottom: 16 }}>
            <div className="stat-card">
              <div className="stat-label">Day P&L</div>
              <div className={clsPnL(r.dayPnl)}>{inr(r.dayPnl)}</div>
              <div className="stat-sub">change since last processed day</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Cash</div>
              <div className="mono">{inr(r.cash)}</div>
              <div className="stat-sub">{((r.cash / r.initialCapital) * 100).toFixed(1)}% parked</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Invested</div>
              <div className="mono">{inr(r.invested)}</div>
              <div className="stat-sub">{((r.invested / r.initialCapital) * 100).toFixed(0)}% of capital at work</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Realized / Unrealized</div>
              <div className={clsPnL(r.realizedPnl)}>{inr(r.realizedPnl)} / <span className={clsPnL(r.unrealizedPnl)}>{inr(r.unrealizedPnl)}</span></div>
              <div className="stat-sub">{r.tradingDays} trading days processed</div>
            </div>
          </div>

          <div className="panel reveal" style={{ marginBottom: 16 }}>
            <div className="panel-title">
              <h3>Equity curve</h3>
              <span className="hint">
                daily MTM on real NSE closes {r.seeded ? '· seeded from ~90d history, then advanced daily' : '· live daily advancement'}
              </span>
            </div>
            <Spark series={r.history} />
          </div>

          <div className="grid-2" style={{ marginBottom: 16 }}>
            <div className="panel reveal">
              <div className="panel-title">
                <h3>Method scorecards</h3>
                <span className="hint">₹20,000 allocated to each</span>
              </div>
              <div className="strat-grid">
                {r.strategies.map((s) => (
                  <div key={s.id} className="strat-card">
                    <div className="strat-head">
                      <span className="strat-name">{s.label}</span>
                      <span className={clsPnL(s.pnl)}>{inr(s.pnl)}</span>
                    </div>
                    <div className="strat-row">
                      <span>Equity</span><b>{inr(s.equity)}</b>
                    </div>
                    <div className="strat-row">
                      <span>Book ₹{Math.round(s.allocPct)}% alloc</span>
                      <b className="mono">{s.trades} trades</b>
                    </div>
                    {s.open && (
                      <div className="strat-open">
                        {s.open.symbol} · {s.open.qty} sh @ {inr(s.open.entryPrice)} · {s.open.heldDays}d
                      </div>
                    )}
                    {!s.open && <div className="strat-open muted">flat — in cash</div>}
                  </div>
                ))}
              </div>
            </div>

            <div className="panel reveal reveal-1">
              <div className="panel-title">
                <h3>Open positions</h3>
                <span className="hint">marked to the latest daily close</span>
              </div>
              {r.openPositions.length ? (
                <div className="table">
                  <div className="tr head">
                    <span>Method</span><span>Symbol</span><span>Qty</span><span>Entry</span><span>Last</span><span>P&L</span>
                  </div>
                  {r.openPositions.map((p) => (
                    <div className="tr" key={p.strategy + p.symbol}>
                      <span className="muted">{p.label}</span>
                      <span><a className="mono" href={`#/stock/${p.symbol}`}>{p.symbol}</a></span>
                      <span className="mono">{p.qty}</span>
                      <span className="mono">{inr(p.entryPrice, 2)}</span>
                      <span className="mono">{inr(p.lastPrice, 2)}</span>
                      <span className={clsPnL(p.unrealized)}>{inr(p.unrealized)} <small>({p.unrealizedPct >= 0 ? '+' : ''}{p.unrealizedPct}%)</small></span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="empty">No open positions — all buckets in cash.</div>
              )}
            </div>
          </div>

          <div className="panel reveal">
            <div className="panel-title">
              <h3>Recent activity</h3>
              <span className="hint">entry on BUY signal · exit on SELL / trailing stop / 20-day hold</span>
            </div>
            <div className="table">
              <div className="tr head">
                <span>Day</span><span>Method</span><span>Symbol</span><span>Side</span><span>Qty</span><span>Price</span><span>P&L</span><span>Why</span>
              </div>
              {r.recentTrades.map((t, i) => (
                <div className="tr" key={`${t.day}-${t.strategy}-${t.symbol}-${i}`}>
                  <span className="mono muted">{t.day}</span>
                  <span className="muted">{t.strategy}</span>
                  <span className="mono">{t.symbol}</span>
                  <span className={t.side === 'BUY' ? 'up' : 'down'}>{t.side}</span>
                  <span className="mono">{t.qty}</span>
                  <span className="mono">{inr(t.price, 2)}</span>
                  <span className={clsPnL(t.pnl)}>{t.side === 'SELL' ? inr(t.pnl) : '—'}</span>
                  <span className="muted" style={{ fontSize: 12 }}>{t.reason}</span>
                </div>
              ))}
              {!r.recentTrades.length && <div className="empty">No trades yet — first run opens positions from the seed window.</div>}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function clsPnL(n: number | null | undefined): string {
  return n == null ? '' : n > 0.005 ? 'up' : n < -0.005 ? 'down' : 'muted';
}