import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { get } from '../api';
import { useLive, refreshSymbols, fetchRelayNews, ensureFundamentals } from '../ws';
import { fmt, fmtPct, fmtCompact, fmtMoney, cls } from '../format';
import { useToast } from '../components/Toasts';
import { DirectionBadge, GradeBadge } from '../components/Badge';
import AdvChart, { type AdvRangeId } from '../components/charts/AdvChart';
import NewsFeed from '../components/NewsFeed';
import CompetitionPanel from '../components/CompetitionPanel';
import ReportsPanel from '../components/ReportsPanel';
import AIAnalyst from '../components/AIAnalyst';
import {
  sma,
  ema,
  rsi,
  macd,
  bollinger,
  atr,
  stochastic,
  supertrend,
  vwap,
  rsiBias,
  macdBias,
  trendBias,
} from '../indicators';
import { computeTech } from '../ai';
import type {
  Instrument,
  Snapshot,
  Signal,
  NewsItem,
  NewsArticle,
  StockAnalysis,
  ScreenResult,
  HistoryRow,
  MgmtAnalysis,
  LegalCase,
  PeerInfo,
} from '../types';

type Tab = 'overview' | 'fundamentals' | 'technical' | 'news' | 'ai';

const RATING_COLOR: Record<string, string> = {
  'Strong Buy': 'var(--up)',
  Buy: 'var(--up)',
  Hold: 'var(--amber)',
  Sell: 'var(--down)',
  'Strong Sell': 'var(--down)',
};

const TABS: { id: Tab; label: string; icon: string }[] = [
  { id: 'overview', label: 'Overview', icon: '◈' },
  { id: 'fundamentals', label: 'Fundamentals', icon: '◉' },
  { id: 'technical', label: 'Technical', icon: '〄' },
  { id: 'ai', label: 'AI Analyst', icon: '✦' },
  { id: 'news', label: 'News', icon: '✉' },
];

function VerdictBar({ mid, low, high, price }: { mid: number; low: number; high: number; price: number }) {
  const lo = Math.min(low, high, mid, price) - 1;
  const hi = Math.max(low, high, mid, price) + 1;
  const pos = (v: number) => `${(((v - lo) / (hi - lo)) * 100).toFixed(1)}%`;
  return (
    <div style={{ margin: '10px 0 2px' }}>
      <div style={{ position: 'relative', height: 10, borderRadius: 6, background: 'linear-gradient(90deg,#ff5c5c,#ffb020 40%,#00d68f 75%,#00d68f)' }}>
        <div style={{ position: 'absolute', left: pos(low), top: -2, height: 14, width: 2, background: 'rgba(232,239,246,0.7)' }} title={`Fair low ${fmt(low)}`} />
        <div style={{ position: 'absolute', left: pos(high), top: -2, height: 14, width: 2, background: 'rgba(232,239,246,0.7)' }} title={`Fair high ${fmt(high)}`} />
        <div
          style={{ position: 'absolute', left: `calc(${pos(price)} - 5px)`, top: -5, width: 10, height: 10, borderRadius: 10, background: '#fff', border: '2px solid #0b0f17' }}
          title={`Current ${fmt(price)}`}
        />
        <div style={{ position: 'absolute', left: pos(mid), top: -4, height: 18, width: 2, background: '#3fd0ea', opacity: 0.8 }} title={`Fair mid ${fmt(mid)}`} />
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10.5, marginTop: 4, color: '#8b98ab' }}>
        <span>Fair low {fmt(low)}</span>
        <span>Fair mid {fmt(mid)}</span>
        <span>Fair high {fmt(high)}</span>
      </div>
    </div>
  );
}

function ScreenBox({ title, icon, result }: { title: string; icon: string; result?: ScreenResult }) {
  if (!result)
    return (
      <div className="panel" style={{ padding: 12 }}>
        <div className="dim" style={{ fontSize: 11, letterSpacing: '0.1em' }}>{icon} {title}</div>
        <div className="empty" style={{ marginTop: 8 }}>No data yet.</div>
      </div>
    );
  return (
    <div className="panel" style={{ padding: 12 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
        <span className="dim" style={{ fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase' }}>{icon} {title}</span>
        <GradeBadge grade={result.grade} />
      </div>
      <div className="muted" style={{ fontSize: 12, lineHeight: 1.5 }}>{result.thesis}</div>
      {result.flags.length > 0 && (
        <div style={{ marginTop: 8, display: 'flex', flexWrap: 'wrap', gap: 4 }}>
          {result.flags.map((f, i) => (
            <span key={i} className="rel-chip" style={{ fontSize: 10.5 }}>{f}</span>
          ))}
        </div>
      )}
    </div>
  );
}

function LegalBadge({ kind }: { kind: LegalCase['kind'] }) {
  return <span className={`legal-badge ${kind}`}>{kind}</span>;
}

function ManagementPanel({ mgmt }: { mgmt: MgmtAnalysis | null }) {
  if (!mgmt)
    return (
      <div className="empty">
        Management &amp; litigation scan pending — generated by the next automation run (Yahoo officers + public news case scan).
      </div>
    );
  const sevColor: Record<string, string> = { good: 'var(--up)', warn: 'var(--amber)', bad: 'var(--down)' };
  return (
    <div>
      <div style={{ display: 'flex', gap: 14, alignItems: 'center', marginBottom: 12, flexWrap: 'wrap' }}>
        <span className="mgmt-score">
          <span className="mgmt-num" style={{ color: mgmt.score >= 70 ? 'var(--up)' : mgmt.score >= 45 ? 'var(--amber)' : 'var(--down)' }}>{mgmt.score}</span>
          <GradeBadge grade={mgmt.grade} />
        </span>
        <span className="hint" style={{ fontSize: 11, color: 'var(--dim)', fontFamily: 'var(--font-mono)' }}>
          last scan {new Date(mgmt.updatedAt).toLocaleString('en-IN', { hour12: false })}
        </span>
      </div>
      <div className="muted" style={{ fontSize: 12.5, lineHeight: 1.5, marginBottom: 12 }}>{mgmt.thesis}</div>

      {mgmt.founders.length > 0 && (
        <div className="rel-chips" style={{ marginBottom: 14 }}>
          {mgmt.founders.map((f, i) => (
            <span key={i} className="rel-chip">
              {f.name} <span className="w">{f.role}</span>
            </span>
          ))}
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 14 }}>
        {mgmt.checks.map((c, i) => (
          <div key={i} style={{ display: 'flex', gap: 8, alignItems: 'flex-start', fontSize: 12.5 }}>
            <span style={{ color: sevColor[c.severity], lineHeight: 1.4 }}>{c.severity === 'good' ? '✓' : c.severity === 'warn' ? '△' : '✕'}</span>
            <span className="muted">{c.label}</span>
          </div>
        ))}
      </div>

      <div style={{ marginTop: 14 }}>
        <div className="panel-title">
          <h3>Legal &amp; regulatory flags</h3>
          <span className="hint">public news scan · 45-day window</span>
        </div>
        {mgmt.cases.length ? (
          <div>
            {mgmt.cases.map((c, i) => (
              <div key={i} className="legal-case">
                <LegalBadge kind={c.kind} />
                <div>
                  <div className="legal-title">
                    <a href={c.url} target="_blank" rel="noopener noreferrer">{c.title}</a>
                  </div>
                  <div className="legal-src">
                    {c.source}{c.date ? ` · ${new Date(c.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}` : ''}
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="dim" style={{ fontSize: 12 }}>
            No criminal, civil or regulatory cases detected in public news for this company — the cleanest possible outcome.
          </div>
        )}
      </div>
    </div>
  );
}

function BiasPill({ bias, label }: { bias: 'bullish' | 'bearish' | 'neutral'; label?: string }) {
  return <span className={`pill-bias ${bias}`}>{label ?? bias}</span>;
}

function IndCard({ name, value, bias, why }: { name: string; value: string; bias: 'bullish' | 'bearish' | 'neutral'; why: string }) {
  return (
    <div className="ind-card">
      <div className="ind-head">
        <span className="ind-name">{name}</span>
        <BiasPill bias={bias} />
      </div>
      <div className="ind-val">{value}</div>
      <div className="ind-why">{why}</div>
    </div>
  );
}

function TechnicalTab({ upper, livePrice }: { upper: string; livePrice?: number | null }) {
  const [range, setRange] = useState<AdvRangeId>('1d');
  const [rows, setRows] = useState<HistoryRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let live = true;
    setLoading(true);
    setErr(null);
    get<{ rows: HistoryRow[] }>(`/api/chart?symbol=${encodeURIComponent(upper)}&range=${range}`)
      .then((r) => {
        if (live) setRows(Array.isArray(r.rows) ? r.rows : []);
      })
      .catch(() => {
        if (live) {
          setRows([]);
          setErr('Chart unavailable — try again in a moment, or check the symbol.');
        }
      })
      .finally(() => {
        if (live) setLoading(false);
      });
    return () => {
      live = false;
    };
  }, [upper, range]);

  const ind = useMemo(() => {
    if (!rows.length) return null;
    const closes = rows.map((r) => r.c);
    const r14 = rsi(closes, 14);
    const macdR = macd(closes, 12, 26, 9);
    const st = stochastic(rows, 14, 3, 3);
    const bb = bollinger(closes, 20, 2);
    const a = atr(rows, 14);
    const stx = supertrend(rows, 14, 3);
    const s50 = sma(closes, 50);
    const s200 = sma(closes, 200);
    const vw = vwap(rows);
    return { closes, r14, macdR, st, bb, a, stx, s50, s200, vw };
  }, [rows]);

  const last = (s: (number | null)[]) => (s.length ? s[s.length - 1] : null);
  const lastValid = (s: (number | null)[]) => {
    for (let i = s.length - 1; i >= 0; i--) if (s[i] != null) return s[i]!;
    return null;
  };

  const price = livePrice ?? rows[rows.length - 1]?.c;

  const cards: { name: string; value: string; bias: 'bullish' | 'bearish' | 'neutral'; why: string }[] = [];
  if (ind) {
    const rv = lastValid(ind.r14);
    if (rv != null) {
      const b = rsiBias(rv);
      cards.push({
        name: 'RSI (14)',
        value: rv.toFixed(1),
        bias: b,
        why:
          b === 'bullish'
            ? rv >= 70
              ? `Momentum ${rv.toFixed(0)} — overheated, pullback risk.`
              : `Momentum ${rv.toFixed(0)} — strong uptrend, buyers in control.`
            : b === 'bearish'
              ? rv <= 30
                ? `Momentum ${rv.toFixed(0)} — oversold, possible bounce.`
                : `Momentum ${rv.toFixed(0)} — sellers in control.`
              : `Momentum ${rv.toFixed(0)} — balanced, no extreme.`,
      });
    }
    const macdLine = lastValid(ind.macdR.line);
    const macdSig = lastValid(ind.macdR.signal);
    if (macdLine != null) {
      const b = macdBias(macdLine, macdSig);
      const cross = macdLine > (macdSig ?? 0) ? 'above' : macdLine < (macdSig ?? 0) ? 'below' : 'at';
      cards.push({
        name: 'MACD (12,26,9)',
        value: `${macdLine.toFixed(2)}`,
        bias: b,
        why: `MACD ${cross} signal line — ${b === 'bullish' ? 'bullish momentum confirmed' : b === 'bearish' ? 'bearish momentum building' : 'flat'}.`,
      });
    }
    const kv = last(ind.st.k);
    const dv = last(ind.st.d);
    if (kv != null && dv != null) {
      const b = kv > dv ? 'bullish' : kv < dv ? 'bearish' : 'neutral';
      cards.push({
        name: 'Stochastic (14,3,3)',
        value: `K ${kv.toFixed(0)} / D ${dv.toFixed(0)}`,
        bias: b,
        why: b === 'bullish' ? `${kv >= 80 ? 'Overbought zone but' : ''} K above D — buying pressure.` : b === 'bearish' ? `${kv <= 20 ? 'Oversold zone but' : ''} K below D — selling pressure.` : 'Bands crossed — no edge.',
      });
    }
    const bbUp = lastValid(ind.bb.upper);
    const bbLo = lastValid(ind.bb.lower);
    if (price != null && bbUp != null && bbLo != null) {
      const pctB = ((price - bbLo) / Math.max(bbUp - bbLo, 0.0001)) * 100;
      const b = pctB > 80 ? 'bearish' : pctB < 20 ? 'bullish' : 'neutral';
      cards.push({
        name: 'Bollinger %B (20,2)',
        value: `${pctB.toFixed(0)}%`,
        bias: b,
        why: b === 'bullish' ? `Price at the ${pctB < -5 ? 'lower band break' : 'lower band'} — stretched down, mean-reversion candidate.` : b === 'bearish' ? `Price riding the ${pctB > 105 ? 'upper band break' : 'upper band'} — stretched up.` : 'Price mid-band — ordinary range.',
      });
    }
    const aVal = lastValid(ind.a);
    if (aVal != null) {
      cards.push({
        name: 'ATR (14)',
        value: fmt(aVal),
        bias: aVal > (price ?? 0) * 0.04 ? 'bearish' : 'neutral',
        why: `Volatility ${aVal > (price ?? 0) * 0.04 ? 'high' : 'normal'} — ${aVal > (price ?? 0) * 0.04 ? 'wider swings, size positions smaller' : 'calmer tape, tighter stops work'}.`,
      });
    }
    const stv = last(ind.stx.line);
    const stdir = last(ind.stx.dir);
    const firstSt = ind.stx.line.find((v) => v != null);
    if (stv != null && stdir != null) {
      const b = stdir === 1 ? 'bullish' : 'bearish';
      const flipped = firstSt != null ? (price != null && firstSt < price ? 'downtrend' : 'uptrend') : '';
      cards.push({
        name: 'Supertrend (14,3)',
        value: `${stdir === 1 ? 'UP' : 'DOWN'} @ ${fmt(stv)}`,
        bias: b,
        why: b === 'bullish' ? `Supertrend flips bullish when price closes above the band — trend filter is ON for longs.` : `Supertrend bearish — avoid longs until a close back above the band.`,
      });
    }
    const st50 = lastValid(ind.s50);
    const st200 = lastValid(ind.s200);
    if (price != null && (st50 != null || st200 != null)) {
      const b = trendBias(price, st50, st200);
      cards.push({
        name: 'Trend (SMA50/200)',
        value: `SMA50 ${st50 != null ? fmt(st50) : '—'} · SMA200 ${st200 != null ? fmt(st200) : '—'}`,
        bias: b,
        why: b === 'bullish' ? 'Golden setup — price above rising averages (older SMA below recent).' : b === 'bearish' ? 'Death setup — price below the averages.' : 'Averages mixed — chop; wait for alignment.',
      });
    }
    if (price != null) {
      const b = price > ind.vw ? 'bullish' : price < ind.vw ? 'bearish' : 'neutral';
      cards.push({
        name: 'VWAP (range)',
        value: fmt(ind.vw),
        bias: b,
        why: `Price ${b === 'bullish' ? 'above' : b === 'bearish' ? 'below' : 'at'} volume-weighted average — intraday ${b} lean.`,
      });
    }
    const vol = rows[rows.length - 1]?.v;
    const avgVol = rows.length > 1 ? rows.reduce((a, r) => a + r.v, 0) / rows.length : 0;
    if (vol != null && avgVol > 0) {
      const ratio = vol / avgVol;
      cards.push({
        name: 'Volume',
        value: `${ratio.toFixed(2)}× avg`,
        bias: ratio > 2 ? 'bearish' : ratio < 0.6 ? 'bullish' : 'neutral',
        why: ratio > 2 ? `Last bar trades at ${ratio.toFixed(1)}× the average — heavy participation (often climax / reversal risk).` : ratio < 0.6 ? `Last bar is quiet, ${ratio.toFixed(1)}× average — thin tape, low conviction.` : 'Volume in line with the average — healthy.',
      });
    }
  }

  return (
    <div>
      <AdvChart symbol={upper} rows={rows} livePrice={livePrice} range={range} onRangeChange={setRange} />
      {loading && <div className="dim" style={{ fontSize: 12, marginTop: 8, textAlign: 'center', fontFamily: 'var(--font-mono)' }}>loading {range} candles…</div>}
      {!loading && err && <div className="empty">{err}</div>}

      <div style={{ marginTop: 16 }}>
        <div className="panel-title">
          <h3>Indicator deck</h3>
          <span className="hint">computed client-side on real {range.toUpperCase()} candles · logic included</span>
        </div>
        {cards.length ? (
          <div className="ind-grid">{cards.map((c, i) => <IndCard key={i} {...c} />)}</div>
        ) : (
          <div className="empty">No indicators yet — need at least ~30 candles for this range.</div>
        )}
      </div>
    </div>
  );
}

export default function Stock() {
  const { symbol = '' } = useParams();
  const upper = symbol.toUpperCase();
  const toast = useToast();

  const snapshots = useLive((s) => s.snapshots);
  const storeInstruments = useLive((s) => s.instruments);
  const universe = useLive((s) => s.universe);
  const fundamentals = useLive((s) => s.fundamentals);
  const newsBySymbol = useLive((s) => s.newsBySymbol);
  const watchlist = useLive((s) => s.watchlist);

  const [instrument, setInstrument] = useState<Instrument | null>(null);
  const [tab, setTab] = useState<Tab>('overview');
  const [signals, setSignals] = useState<Signal[]>([]);
  const [stockNews, setStockNews] = useState<NewsItem[]>([]);
  const [stockNewsArt, setStockNewsArt] = useState<NewsArticle[]>([]);
  const [ovRange, setOvRange] = useState<AdvRangeId>('1d');
  const [dayRows, setDayRows] = useState<HistoryRow[]>([]);
  const [dayLoading, setDayLoading] = useState(true);
  const [aiPrompt, setAiPrompt] = useState<string | null>(null);

  const [importState, setImportState] = useState<'idle' | 'busy' | 'queued' | 'error'>('idle');
  const requestImport = async () => {
    if (importState === 'busy' || importState === 'queued') return;
    setImportState('busy');
    try {
      const r = await fetch(`/api/import?symbol=${encodeURIComponent(upper)}`, { cache: 'no-store' });
      const j = (await r.json().catch(() => null)) as { queued?: boolean; error?: string; detail?: string } | null;
      if (r.ok && j?.queued) {
        setImportState('queued');
        toast(`Import queued — ${upper} will be fully covered in ~2 minutes`, 'ok');
      } else {
        setImportState('error');
        toast(j?.error ?? `Import failed${j?.detail ? `: ${j.detail}` : ''}`, 'err');
      }
    } catch {
      setImportState('error');
      toast('Import request failed — is the deployed relay reachable?', 'err');
    }
  };

  const snap: Snapshot | undefined = snapshots[upper];
  const analysis: StockAnalysis | undefined = fundamentals[upper];
  const watch = watchlist.includes(upper);

  useEffect(() => {
    setInstrument((prev) => {
      const fromStore = storeInstruments.find((i) => i.symbol === upper);
      if (fromStore) return fromStore;
      const a = fundamentals[upper];
      if (a) return { id: 0, symbol: upper, name: a.name ?? upper, sector: a.sector ?? '', isin: '', exchange: 'NSE', marketCap: a.marketCap ?? 0, basePrice: a.price };
      const s = snapshots[upper];
      const fromUni = universe.find((u) => u.symbol === upper);
      if (fromUni) {
        return { id: 0, symbol: upper, name: fromUni.name, sector: `${fromUni.exchange} · ${fromUni.cap}`, isin: fromUni.isin, exchange: fromUni.exchange, marketCap: fromUni.mktCap ?? 0, basePrice: s?.price ?? 0 };
      }
      if (/^[A-Z0-9][A-Z0-9&-]{0,19}$/.test(upper)) {
        return { id: 0, symbol: upper, name: upper, sector: 'NSE/BSE', isin: '', exchange: 'NSE', marketCap: 0, basePrice: s?.price ?? 0 };
      }
      return prev;
    });
  }, [upper, storeInstruments, snapshots, fundamentals, universe]);

  useEffect(() => {
    setSignals([]);
    setStockNews([]);
    setStockNewsArt([]);
    setTab('overview');
    setOvRange('1d');
    setDayRows([]);
    void refreshSymbols([upper]);
    // any symbol — inside or outside the nightly universe — gets full
    // fundamentals/AI/competition data on demand via the free relay
    void ensureFundamentals([upper]);
    void fetchRelayNews(upper).then((arts) => {
      if (arts.length) setStockNewsArt(arts);
    });

    get<Signal[]>(`/api/instruments/${upper}/signals?limit=30`)
      .then(setSignals)
      .catch(() => {});
    get<NewsItem[]>(`/api/instruments/${upper}/news?limit=12`)
      .then(setStockNews)
      .catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [upper]);

  useEffect(() => {
    const art = newsBySymbol[upper];
    if (art?.length) setStockNewsArt(art);
  }, [newsBySymbol, upper]);

  useEffect(() => {
    let live = true;
    setDayLoading(true);
    get<{ rows: HistoryRow[] }>(`/api/chart?symbol=${encodeURIComponent(upper)}&range=${ovRange}`)
      .then((r) => {
        if (live) setDayRows(Array.isArray(r.rows) ? r.rows : []);
      })
      .catch(() => {
        if (live) setDayRows([]);
      })
      .finally(() => {
        if (live) setDayLoading(false);
      });
    return () => {
      live = false;
    };
  }, [upper, ovRange]);

  const changePct = snap?.changePct;
  const tech = useMemo(() => computeTech(dayRows), [dayRows]);

  const toggleWatch = () => {
    const added = useLive.getState().toggleWatch(upper);
    toast(added ? `Added ${upper} to watchlist` : `Removed ${upper} from watchlist`, 'ok');
  };

  if (!instrument) {
    return <div className="empty">Instrument {upper} is not a listed NSE/BSE ticker.</div>;
  }

  const name = instrument?.name ?? analysis?.name ?? upper;
  const sector = instrument?.sector ?? analysis?.sector ?? null;
  const verdict = analysis?.verdict;
  const mgmt = analysis?.management ?? null;
  const livePrice = snap?.price ?? analysis?.price;
  const ltStance = analysis?.opinion?.stance ?? (verdict ? (verdict.rating.includes('Buy') ? 'BUY' : verdict.rating.includes('Sell') ? 'SELL' : 'HOLD') : null);
  const peerList: PeerInfo[] = analysis?.peers?.length
    ? analysis.peers
    : (storeInstruments.length ? storeInstruments : universe.map((u, i) => ({ id: i, symbol: u.symbol, name: u.name, sector: `${u.exchange} · ${u.cap}`, isin: u.isin, exchange: u.exchange, marketCap: u.mktCap ?? 0, basePrice: 0 })))
        .filter((i) => i.symbol !== upper && i.sector && sector && i.sector === sector)
        .slice(0, 8)
        .map((i) => ({ symbol: i.symbol, name: i.name, industry: null, sector: i.sector }));

  return (
    <div>
      <div className="stock-header">
        <div className="stock-title">
          <div className="sym">{upper}</div>
          <div className="nm">{name} · {sector ?? '—'}</div>
        </div>
        <div className="stock-price-block">
          <div className={cls('stock-price', (changePct ?? 0) >= 0 ? 'up' : 'down')}>{fmt(snap?.price ?? analysis?.price ?? instrument?.basePrice)}</div>
          <div className={cls('stock-change', (changePct ?? 0) >= 0 ? 'up' : 'down')}>
            {changePct != null ? `${fmtPct(changePct)}  (${fmt(snap?.change, 2)})` : '—'}
          </div>
        </div>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <button className={cls('btn', watch && 'primary')} onClick={toggleWatch}>
            {watch ? '★ In Watchlist' : '☆ Add to Watchlist'}
          </button>
        </div>
      </div>

      <div className="ohlc-strip" style={{ marginBottom: 18 }}>
        <span>Open <b>{fmt(snap?.dayOpen)}</b></span>
        <span>High <b className="up">{fmt(snap?.dayHigh)}</b></span>
        <span>Low <b className="down">{fmt(snap?.dayLow)}</b></span>
        <span>Prev Close <b>{fmt(snap?.prevClose)}</b></span>
        <span>Volume <b>{fmtCompact(snap?.dayVolume)}</b></span>
        <span>Day Range <b>{fmt(snap?.dayLow)} – {fmt(snap?.dayHigh)}</b></span>
      </div>

      <div className="tabs">
        {TABS.map((t) => (
          <button key={t.id} className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}>
            {t.icon} {t.label}
          </button>
        ))}
      </div>

      {tab === 'overview' && (
        <div>
          <div className="grid-2-1" style={{ marginBottom: 16 }}>
            <div className="chart-box reveal">
              <div className="panel-title">
                <h3>Price history</h3>
                <span className="hint">
                  {dayRows.length > 1
                    ? `${ovRange.toUpperCase()} · real NSE · IST`
                    : dayLoading
                      ? 'loading candles…'
                      : 'chart feed unavailable — retry in a moment'}
                </span>
              </div>
              {dayRows.length > 1 ? (
                <AdvChart symbol={upper} rows={dayRows} livePrice={livePrice} range={ovRange} onRangeChange={setOvRange} />
              ) : dayLoading ? (
                <div className="empty" style={{ minHeight: 330, display: 'grid', placeItems: 'center' }}>
                  <div>
                    <div style={{ fontSize: 22, marginBottom: 8 }}>▤</div>
                    Loading {ovRange.toUpperCase()} candles…
                  </div>
                </div>
              ) : (
                <div className="empty" style={{ minHeight: 330, display: 'grid', placeItems: 'center' }}>
                  <div>
                    <div style={{ fontSize: 22, marginBottom: 8 }}>▤</div>
                    No candles for {ovRange.toUpperCase()} yet. Open Technical or pick another range.
                    <div style={{ marginTop: 10 }}>
                      <div className="range-tabs" style={{ justifyContent: 'center' }}>
                        {(['1d', '5d', '1mo', '6mo', '1y', '5y'] as AdvRangeId[]).map((r) => (
                          <button key={r} className={ovRange === r ? 'active' : ''} onClick={() => setOvRange(r)}>{r.toUpperCase()}</button>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            <div className="panel reveal reveal-1">
              <div className="panel-title">
                <h3>Analyst verdict</h3>
                <span className="hint">Buffett · Lynch · Graham</span>
              </div>
              {analysis ? (
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                    <span className="mono dim" style={{ fontSize: 12 }}>Rating</span>
                    <span className="mono" style={{ fontSize: 15, fontWeight: 800, color: RATING_COLOR[verdict?.rating ?? 'Hold'] }}>{verdict?.rating}</span>
                    <GradeBadge grade={verdict?.grade ?? 'C'} />
                    <span className="mono dim" style={{ fontSize: 13, fontWeight: 700, marginLeft: 'auto' }}>{verdict?.score}/100</span>
                  </div>
                  <div className="muted" style={{ fontSize: 12.5, lineHeight: 1.55, marginBottom: 6 }}>{verdict?.summary}</div>
                  {verdict && <VerdictBar mid={verdict.fairValueMid} low={verdict.fairValueLow} high={verdict.fairValueHigh} price={analysis.price} />}
                  <div className="dual-verdict">
                    <div className="dv-card">
                      <div className="dv-k">Technical (short-term)</div>
                      <div className="dv-v" style={{ color: tech?.verdict.stance === 'BUY' ? 'var(--up)' : tech?.verdict.stance === 'SELL' ? 'var(--down)' : 'var(--amber)' }}>
                        {tech ? `${tech.verdict.stance} · ${tech.verdict.trend}` : 'loading…'}
                      </div>
                      <div className="dv-why">{tech?.verdict.why[0] ?? 'Waiting on 1D candles for breakout / trend read.'}</div>
                    </div>
                    <div className="dv-card">
                      <div className="dv-k">Fundamental (3–5y)</div>
                      <div className="dv-v" style={{ color: ltStance === 'BUY' ? 'var(--up)' : ltStance === 'SELL' ? 'var(--down)' : 'var(--amber)' }}>
                        {ltStance ?? 'pending'}{analysis?.opinion ? ` · ${analysis.opinion.conviction}%` : verdict ? ` · ${verdict.score}/100` : ''}
                      </div>
                      <div className="dv-why">{analysis?.opinion?.thesis ?? verdict?.summary ?? 'Long-term screen pending.'}</div>
                    </div>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 10 }}>
                    <ScreenInline grade={analysis.screens.buffett.grade} label="Buffett" score={analysis.screens.buffett.score} />
                    <ScreenInline grade={analysis.screens.lynch.grade} label="Lynch" score={analysis.screens.lynch.score} />
                    <ScreenInline grade={analysis.screens.graham.grade} label="Graham" score={analysis.screens.graham.score} />
                  </div>
                </div>
              ) : (
                <div className="empty">Analyst model pending — appears after the next automation run.</div>
              )}
            </div>
          </div>

          <div className="grid-2" style={{ marginBottom: 16 }}>
            <div className="panel reveal">
              <div className="panel-title"><h3>Signal history — {upper}</h3><span className="hint">algorithm engine</span></div>
              <div style={{ maxHeight: 300, overflowY: 'auto' }}>
                <div className="feed">
                  {signals.map((s) => (
                    <div key={s.id} className="feed-item">
                      <div className="feed-main">
                        <div className="feed-head"><DirectionBadge dir={s.direction} /></div>
                        <div className="feed-reason">{s.reason}</div>
                        <div className="feed-meta">
                          <span className="strat">{s.strategy}</span>
                          <span className="px">@{fmt(s.price)}</span>
                          <span className="t">{new Date(s.ts).toLocaleString('en-IN', { hour12: false })}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                  {!signals.length && <div className="empty">No signals yet for {upper}.</div>}
                </div>
              </div>
            </div>

            <div className="panel reveal reveal-1">
              <div className="panel-title"><h3>Why this rating</h3><span className="hint">rule-based, reproducible</span></div>
              {analysis ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                  <WhyScreen icon="🧊" name="Buffett" result={analysis.screens.buffett} />
                  <WhyScreen icon="⚡" name="Lynch" result={analysis.screens.lynch} />
                  <WhyScreen icon="🛡" name="Graham" result={analysis.screens.graham} />
                </div>
              ) : (
                <div className="empty">No screens yet.</div>
              )}
            </div>
          </div>

          <CompetitionPanel symbol={upper} peers={peerList} onContext={(q) => { setAiPrompt(q); setTab('ai'); }} />
          <ReportsPanel symbol={upper} name={name} reports={analysis?.reports ?? null} />
        </div>
      )}

      {tab === 'technical' && (
        <div>
          <TechnicalTab upper={upper} livePrice={livePrice} />
        </div>
      )}

      {tab === 'fundamentals' && (
        <div>
          {analysis ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div className="panel">
                <div className="panel-title">
                  <h3>Fundamentals &amp; fair value</h3>
                  <span className="hint">real Yahoo data · ratings with reasoning</span>
                </div>
                <div style={{ display: 'flex', gap: 22, flexWrap: 'wrap', alignItems: 'center', marginBottom: 14 }}>
                  <svg width="150" height="150" className="gauge" style={{ width: 150, height: 150 }}>
                    <defs>
                      <linearGradient id="gauge-grad" x1="0%" y1="0%" x2="100%" y2="0%">
                        <stop offset="0%" stopColor="#ff5c5c" />
                        <stop offset="50%" stopColor="#ffb020" />
                        <stop offset="100%" stopColor="#00d68f" />
                      </linearGradient>
                    </defs>
                    <circle className="ring-bg" cx="75" cy="75" r="62" fill="none" strokeWidth="12" />
                    <circle
                      className="ring-fg"
                      cx="75" cy="75" r="62" fill="none" strokeWidth="12"
                      strokeDasharray={`${2 * Math.PI * 62}`}
                      strokeDashoffset={`${2 * Math.PI * 62 * (1 - Math.min(100, verdict?.score ?? 0) / 100)}`}
                    />
                    <text x="75" y="86" textAnchor="middle" fill="#e8eff6" style={{ font: '900 34px Archivo', letterSpacing: -1 }}>
                      {verdict?.score}
                    </text>
                    <text x="75" y="104" textAnchor="middle" fill="#8b98ab" style={{ font: "700 10px 'IBM Plex Mono', monospace", letterSpacing: '0.1em' }}>
                      {verdict?.grade ?? '–'}
                    </text>
                  </svg>
                  <div style={{ flex: 1, minWidth: 260 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                      <span className="mono dim" style={{ fontSize: 12 }}>Analyst Verdict</span>
                      <span className="mono" style={{ fontSize: 13, fontWeight: 700, color: RATING_COLOR[verdict?.rating ?? 'Hold'] }}>{verdict?.rating}</span>
                      <GradeBadge grade={verdict?.grade ?? 'C'} />
                    </div>
                    <div className="muted" style={{ fontSize: 12, lineHeight: 1.55, marginBottom: 4 }}>{verdict?.summary}</div>
                    {verdict?.targetMean != null && (
                      <div className="dim" style={{ fontSize: 11, marginBottom: 2 }}>
                        Street target {fmt(verdict.targetMean)}{verdict.analysts ? ` from ${verdict.analysts} analysts` : ''} · Fair value {fmtMoney(verdict.fairValueMid)} · MoS {verdict.marginOfSafety > 0 ? '+' : ''}{verdict.marginOfSafety}%
                      </div>
                    )}
                    {verdict && <VerdictBar mid={verdict.fairValueMid} low={verdict.fairValueLow} high={verdict.fairValueHigh} price={analysis.price} />}
                  </div>
                </div>

                <div className="ratio-grid" style={{ marginBottom: 14 }}>
                  <div className="ratio"><div className="k">P/E</div><div className="v">{analysis.metrics.pe?.toFixed(1) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">P/B</div><div className="v">{analysis.metrics.pb?.toFixed(1) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">P/S</div><div className="v">{analysis.metrics.ps?.toFixed(2) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">PEG</div><div className="v">{analysis.metrics.peg?.toFixed(2) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">ROE</div><div className="v">{analysis.metrics.roe?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">ROCE</div><div className="v">{analysis.metrics.roce?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">ROA</div><div className="v">{analysis.metrics.roa?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">Growth</div><div className="v">{analysis.metrics.growth?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">Rev Gth</div><div className="v">{analysis.metrics.revenueGrowth?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">Net Mar</div><div className="v">{analysis.metrics.netMargin?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">Op Mar</div><div className="v">{analysis.metrics.operatingMargin?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">Gross Mar</div><div className="v">{analysis.metrics.grossMargin?.toFixed(1) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">D/E</div><div className="v">{analysis.metrics.debtToEquity?.toFixed(2) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">Cur Ratio</div><div className="v">{analysis.metrics.currentRatio?.toFixed(2) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">Qk Ratio</div><div className="v">{analysis.metrics.quickRatio?.toFixed(2) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">EPS</div><div className="v">{fmt(analysis.metrics.eps)}</div></div>
                  <div className="ratio"><div className="k">BV/Sh</div><div className="v">{fmt(analysis.metrics.bookValue)}</div></div>
                  <div className="ratio"><div className="k">Beta</div><div className="v">{analysis.metrics.beta?.toFixed(2) ?? '—'}</div></div>
                  <div className="ratio"><div className="k">Div Yld</div><div className="v">{analysis.metrics.dividendYield?.toFixed(2) ?? '—'}%</div></div>
                  <div className="ratio"><div className="k">Mkt Cap</div><div className="v">{analysis.marketCap ? fmtCompact(analysis.marketCap) : '—'}</div></div>
                </div>
                <div className="dim" style={{ fontSize: 11, lineHeight: 1.8, marginBottom: 4 }}>
                  {instrument?.isin && <span>ISIN <span className="mono">{instrument.isin}</span> · </span>}
                  {instrument?.exchange && <span>listed on {instrument.exchange}</span>}
                  {analysis.metrics.promoterHolding != null && (
                    <span> · Promoter {analysis.metrics.promoterHolding}% · FII {analysis.metrics.fiiHolding ?? 0}%</span>
                  )}
                  <span> · 52-wk {fmt(analysis.metrics.fiftyTwoWeekLow)}–{fmt(analysis.metrics.fiftyTwoWeekHigh)}</span>
                  {analysis.metrics.targetMean != null && (
                    <span> · Street target {fmt(analysis.metrics.targetMean)} ({analysis.metrics.analysts ?? 0} analysts)</span>
                  )}
                </div>
              </div>

              <div className="panel">
                <div className="panel-title">
                  <h3>Screen breakdown — why the score</h3>
                  <span className="hint">three classic disciplines</span>
                </div>
                <div className="grid-3">
                  <ScreenBox title="Warren Buffett" icon="🧊" result={analysis.screens.buffett} />
                  <ScreenBox title="Peter Lynch" icon="⚡" result={analysis.screens.lynch} />
                  <ScreenBox title="Benjamin Graham" icon="🛡" result={analysis.screens.graham} />
                </div>
              </div>

              <div className="panel">
                <div className="panel-title">
                  <h3>Management &amp; legal risk</h3>
                  <span className="hint">officers + criminal/civil/regulatory scans</span>
                </div>
                <ManagementPanel mgmt={mgmt} />
              </div>
            </div>
          ) : (
            <div className="panel">
              <div className="empty">
                {upper} has no fundamental model yet — it can be added to platform coverage on demand.
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, padding: '2px 0 16px' }}>
                <button
                  className="btn primary"
                  disabled={importState === 'busy' || importState === 'queued'}
                  onClick={requestImport}
                >
                  {importState === 'queued' ? 'Import queued — refresh in ~2 min' : importState === 'busy' ? 'Queuing…' : `Import ${upper} into coverage`}
                </button>
                <div className="hint">
                  Runs a small automation that fetches real fundamentals, Screener.in competitors &amp; the last 7 days of
                  news, then publishes it for everyone. Instant view still works below the banner meanwhile.
                </div>
                {importState === 'error' && (
                  <div className="dim" style={{ color: 'var(--down)', fontSize: 11.5 }}>
                    The last import attempt failed — you can retry, or the nightly coverage batch will reach this symbol eventually.
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      )}

      {tab === 'ai' && (
        <AIAnalyst upper={upper} prompt={aiPrompt} onPromptConsumed={() => setAiPrompt(null)} />
      )}

      {tab === 'news' && (
        <div className="grid-2">
          <div className="panel">
            <div className="panel-title">
              <h3>News — {upper}</h3>
              <span className="hint">Google News · live</span>
            </div>
            {stockNewsArt.length ? (
              <div className="stock-news-list">
                {stockNewsArt.map((a, i) => (
                  <div key={i} className="news-art">
                    <a href={a.url} target="_blank" rel="noopener noreferrer">{a.title}</a>
                    <div className="news-meta">
                      <span>{a.source}</span>
                      <span>{new Date(a.publishedAt).toLocaleString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', hour12: false })}</span>
                    </div>
                  </div>
                ))}
              </div>
            ) : stockNews.length ? (
              <div style={{ maxHeight: 480, overflowY: 'auto' }}>
                <NewsFeed items={stockNews} limit={12} />
              </div>
            ) : (
              <div className="empty">No recent headlines for {upper} from Google News.</div>
            )}
          </div>

          <div className="panel">
            <div className="panel-title"><h3>Signal history</h3><span className="hint">algorithm engine</span></div>
            <div style={{ maxHeight: 480, overflowY: 'auto' }}>
              <div className="feed">
                {signals.map((s) => (
                  <div key={s.id} className="feed-item">
                    <div className="feed-main">
                      <div className="feed-head"><DirectionBadge dir={s.direction} /></div>
                      <div className="feed-reason">{s.reason}</div>
                      <div className="feed-meta">
                        <span className="strat">{s.strategy}</span>
                        <span className="px">@{fmt(s.price)}</span>
                        <span className="t">{new Date(s.ts).toLocaleString('en-IN', { hour12: false })}</span>
                      </div>
                    </div>
                  </div>
                ))}
                {!signals.length && <div className="empty">No signals yet for {upper}.</div>}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ScreenInline({ label, score, grade }: { label: string; score: number; grade: string }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 2, alignItems: 'center', fontSize: 11 }}>
      <span className="dim" style={{ fontFamily: 'var(--font-mono)', letterSpacing: '0.06em' }}>{label}</span>
      <span style={{ fontWeight: 800 }}>{score}<span className="dim">/100</span></span>
      <GradeBadge grade={grade} />
    </div>
  );
}

function WhyScreen({ icon, name, result }: { icon: string; name: string; result: ScreenResult }) {
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
        <span className="dim" style={{ fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase' }}>{icon} {name}</span>
        <GradeBadge grade={result.grade} />
      </div>
      <div className="muted" style={{ fontSize: 12, lineHeight: 1.5, marginBottom: 6 }}>{result.thesis}</div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
        {result.flags.map((f, i) => (
          <span key={i} className="rel-chip" style={{ fontSize: 10.5 }}>{f}</span>
        ))}
      </div>
    </div>
  );
}